import { openapiSchemaToJsonSchema } from "@openapi-contrib/openapi-schema-to-json-schema";
import { compile } from "json-schema-to-typescript";
import nunjucks from "nunjucks";
import prettier from "prettier";
import fs from "fs";
import path from "path";

type AnySchema = Record<string, any>;

/** Header inserted at the top of every generated file. */
const FILE_HEADER = "// This file is automatically generated, do not edit this file";

// ===========================================================================
// Build orchestrator
// ===========================================================================

/**
 * Orchestrates SDK code generation from the OpenAPI spec.
 *
 * Mirrors the structure of the Python `GenerateClientBuildHook`: a single entry
 * point (`run`) that reads the spec, then delegates to focused generator methods
 * for the model type declarations and the HTTP client.
 */
class SdkBuilder {
    private readonly templatesDir: string;
    private readonly openapiPath: string;
    private readonly outputDir: string;
    private readonly modelOutput: string;
    private readonly clientOutput: string;

    constructor(root: string) {
        this.templatesDir = path.join(root, "templates");
        this.openapiPath = path.join(root, "openapi.json");
        this.outputDir = path.join(root, "src");
        this.modelOutput = path.join(this.outputDir, "types.ts");
        this.clientOutput = path.join(this.outputDir, "client.ts");
    }

    /** Run code generation: read the spec, then generate models and client. */
    async run(): Promise<void> {
        const spec: AnySchema = JSON.parse(await fs.promises.readFile(this.openapiPath, "utf-8"));
        await this.generateModels(spec);
        await this.generateClient(spec);
        await this.formatOutputs();
    }

    /**
     * Generate `src/types.ts` from the OpenAPI spec.
     *
     * Registers every component/inline schema as a JSON-Schema definition,
     * normalises titles, resolves collisions, then compiles the whole set with
     * json-schema-to-typescript in a single pass.
     */
    async generateModels(spec: AnySchema): Promise<void> {
        // Accumulate all definitions here; keyed by name to naturally deduplicate.
        const definitions: Record<string, AnySchema> = {};

        /** Convert an OpenAPI schema and register it as a definition. */
        const register = (schema: AnySchema, hint: string): void => {
            // Skip pure $ref schemas – they are already covered by the referenced definition.
            const keys = Object.keys(schema);
            if (keys.length === 1 && keys[0] === "$ref") return;

            const key = definitionKey(schema, hint);
            if (definitions[key]) return; // already registered – skip to avoid duplicates
            definitions[key] = convertSchema(schema);
        };

        // 1. Register all named component schemas under their component key (not their title),
        //    because rewritten $refs point to the component key name.
        for (const [name, schema] of Object.entries<AnySchema>(spec?.components?.schemas ?? {})) {
            if (!definitions[name]) {
                definitions[name] = convertSchema(schema);
            }
        }

        // 2. Register inline schemas from request bodies and responses across all paths.
        //    When a schema has no title, derive one from the operationId in PascalCase,
        //    suffixed with `Request` or `Response`.
        for (const [apiPath, pathItem] of Object.entries<any>(spec?.paths ?? {})) {
            for (const [method, operation] of Object.entries<any>(pathItem)) {
                if (typeof operation !== "object" || operation === null) continue;

                const base = toPascalCase(operation.operationId ?? `${method}_${apiPath}`);

                if (operation.requestBody?.content) {
                    for (const schema of contentSchemas(operation.requestBody.content)) {
                        register(schema, `${base}Request`);
                    }
                }

                for (const response of Object.values<any>(operation.responses ?? {})) {
                    if (!response?.content) continue;
                    for (const schema of contentSchemas(response.content)) {
                        register(schema, `${base}Response`);
                    }
                }
            }
        }

        // 3. Ensure every nested object with ≥1 property has a title.
        for (const [name, schema] of Object.entries(definitions)) {
            definitions[name] = ensureTitles(schema, name);
        }

        // 4. Build a single root schema containing all definitions and compile once.
        //    unreachableDefinitions: true ensures every definition is emitted even if
        //    nothing at the root level references it.
        let rootSchema: AnySchema = {
            title: "ApiTypes",
            type: "object",
            definitions,
        };

        // 5. Deduplicate titles: when ≥2 objects share a title, prefix each with its
        //    nearest titled ancestor, repeating until all titles are unique.
        rootSchema = deduplicateTitles(rootSchema);

        const compiled = await compile(rootSchema, "ApiTypes", {
            additionalProperties: false,
            format: false,
            unreachableDefinitions: true,
        });

        await fs.promises.writeFile(this.modelOutput, compiled, "utf-8");
    }

    /** Generate `src/client.ts` from the OpenAPI spec using the Nunjucks template. */
    async generateClient(spec: AnySchema): Promise<void> {
        const operations = buildOperations(spec);

        const imports = new Set<string>();
        for (const op of operations) {
            if (op.request_class) imports.add(op.request_class);
            imports.add(op.response_class);
        }
        const sortedImports = [...imports].sort();

        const env = nunjucks.configure(this.templatesDir, {
            autoescape: false,
            trimBlocks: false,
            lstripBlocks: false,
        });

        const rendered = env.render("client.ts.njk", {
            operations,
            imports: sortedImports,
            header: FILE_HEADER,
        });

        await fs.promises.writeFile(this.clientOutput, rendered, "utf-8");
    }

    /** Format all generated files with Prettier as the final build step. */
    async formatOutputs(): Promise<void> {
        const files = [this.modelOutput, this.clientOutput];
        for (const file of files) {
            const source = await fs.promises.readFile(file, "utf-8");
            const config = await prettier.resolveConfig(file);
            const formatted = await prettier.format(source, {
                ...config,
                filepath: file,
            });
            await fs.promises.writeFile(file, formatted, "utf-8");
        }
    }
}

// ===========================================================================
// Shared helpers
// ===========================================================================

/** Convert an arbitrary string (spaces, underscores, hyphens) into PascalCase. */
function toPascalCase(raw: string): string {
    return raw
        .split(/[^a-zA-Z0-9]+/)
        .filter(Boolean)
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
        .join("");
}

/** Convert a snake_case or hyphenated name to camelCase (leaves camelCase intact). */
function toCamelCase(raw: string): string {
    const parts = raw.split(/[_-]+/).filter(Boolean);
    if (parts.length === 0) return raw;
    return (
        parts[0] +
        parts
            .slice(1)
            .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
            .join("")
    );
}

// ===========================================================================
// Model generation helpers
// ===========================================================================

/** Recursively rewrite $ref values from #/components/schemas/X to #/definitions/X */
function rewriteRefs(node: any): any {
    if (Array.isArray(node)) {
        return node.map(rewriteRefs);
    }
    if (node !== null && typeof node === "object") {
        const result: any = {};
        for (const [key, value] of Object.entries(node)) {
            if (key === "$ref" && typeof value === "string") {
                result[key] = value.replace(/^#\/components\/schemas\//, "#/definitions/");
            } else {
                result[key] = rewriteRefs(value);
            }
        }
        return result;
    }
    return node;
}

/**
 * Recursively replace `allOf` with the non-standard `extends` keyword understood by
 * json-schema-to-typescript.
 *
 * - Pure $ref entries in allOf  → put into `extends` (object or array)
 * - Inline object entries        → merged directly into the parent schema
 */
function resolveAllOf(node: any): any {
    if (Array.isArray(node)) {
        return node.map(resolveAllOf);
    }
    if (node !== null && typeof node === "object") {
        // Recursively process all children first (except allOf – handled below)
        const result: any = {};
        for (const [key, value] of Object.entries(node)) {
            if (key !== "allOf") {
                result[key] = resolveAllOf(value);
            }
        }

        if (Array.isArray(node.allOf)) {
            const processed = node.allOf.map(resolveAllOf);
            const isPureRef = (s: any) =>
                s !== null && typeof s === "object" && Object.keys(s).length === 1 && "$ref" in s;

            const refs = processed.filter(isPureRef);
            const inlines = processed.filter((s: any) => !isPureRef(s));

            // Merge inline schemas up into the result
            for (const inline of inlines) {
                for (const [k, v] of Object.entries<any>(inline)) {
                    if (k === "properties") {
                        result.properties = { ...result.properties, ...v };
                    } else if (k === "required") {
                        const existing: string[] = result.required ?? [];
                        result.required = Array.from(new Set([...existing, ...v]));
                    } else if (!(k in result)) {
                        // Only copy fields not already present on the parent
                        result[k] = v;
                    }
                }
            }

            // Put $ref entries into extends
            if (refs.length === 1) {
                result.extends = refs[0];
            } else if (refs.length > 1) {
                result.extends = refs;
            }
        }

        return result;
    }
    return node;
}

/**
 * Recursively ensure that every object schema with at least one explicit property
 * has a `title` field.  When one is missing, the PascalCase version of the
 * property key under which this schema lives is used as the title.
 */
function ensureTitles(node: any, fieldName?: string): any {
    if (Array.isArray(node)) {
        return node.map((item) => ensureTitles(item, fieldName));
    }
    if (node !== null && typeof node === "object") {
        let result: any = { ...node };

        // Assign a title when the schema is an object with ≥1 explicit property but no title.
        const hasProperties =
            result.properties &&
            typeof result.properties === "object" &&
            Object.keys(result.properties).length > 0;
        if (hasProperties && !result.title && fieldName) {
            result.title = toPascalCase(fieldName);
        }

        // Recurse into `properties`, carrying each property key as the hint.
        if (result.properties) {
            const newProps: any = {};
            for (const [propName, propSchema] of Object.entries<any>(result.properties)) {
                newProps[propName] = ensureTitles(propSchema, propName);
            }
            result.properties = newProps;
        }

        // Recurse into other schema composition / wrapper keywords.
        for (const key of ["items", "additionalProperties", "not"]) {
            if (result[key] && typeof result[key] === "object") {
                result[key] = ensureTitles(result[key], key);
            }
        }
        for (const key of ["anyOf", "oneOf", "allOf", "extends"]) {
            if (Array.isArray(result[key])) {
                result[key] = result[key].map((s: any) => ensureTitles(s, fieldName));
            }
        }

        return result;
    }
    return node;
}

/**
 * Repeatedly scan the schema tree for title collisions.  When two or more titled
 * objects share the same title, every conflicting node gets its title prefixed with
 * the title of its nearest titled ancestor.  The loop continues until no two nodes
 * carry the same title.
 */
function deduplicateTitles(rootSchema: AnySchema): AnySchema {
    let schema: AnySchema = JSON.parse(JSON.stringify(rootSchema));

    for (;;) {
        // --- pass 1: count how many times each title appears ---
        const counts = new Map<string, number>();
        (function count(node: any): void {
            if (Array.isArray(node)) {
                node.forEach(count);
                return;
            }
            if (node !== null && typeof node === "object") {
                if (typeof node.title === "string") {
                    counts.set(node.title, (counts.get(node.title) ?? 0) + 1);
                }
                for (const v of Object.values(node)) count(v);
            }
        })(schema);

        const duplicates = new Set<string>(
            [...counts.entries()].filter(([, n]) => n > 1).map(([t]) => t),
        );
        if (duplicates.size === 0) break;

        // --- pass 2: rename conflicting titles, carrying the nearest parent title ---
        (function rename(node: any, parentTitle: string | undefined): void {
            if (Array.isArray(node)) {
                node.forEach((item) => rename(item, parentTitle));
                return;
            }
            if (node !== null && typeof node === "object") {
                const originalTitle: string | undefined = node.title;
                if (
                    typeof originalTitle === "string" &&
                    duplicates.has(originalTitle) &&
                    parentTitle
                ) {
                    node.title = parentTitle + originalTitle;
                }
                const effectiveParent = typeof node.title === "string" ? node.title : parentTitle;
                for (const [k, v] of Object.entries(node)) {
                    if (k !== "title") rename(v, effectiveParent);
                }
            }
        })(schema, undefined);
    }

    return schema;
}

/** Derive a PascalCase definition key from a schema's title, falling back to a provided hint. */
function definitionKey(schema: AnySchema, hint: string): string {
    return toPascalCase(schema.title ?? hint);
}

/** Yield every schema found under a content map (e.g. request/response `content`). */
function* contentSchemas(contentMap: Record<string, any>): Generator<AnySchema> {
    for (const mediaType of Object.values(contentMap ?? {})) {
        if (mediaType?.schema) yield mediaType.schema;
    }
}

/** Full pipeline: rewrite refs → OpenAPI→JSON Schema → resolve allOf→extends */
function convertSchema(schema: AnySchema): AnySchema {
    return resolveAllOf(openapiSchemaToJsonSchema(rewriteRefs(schema))) as AnySchema;
}

// ===========================================================================
// Client generation helpers
// ===========================================================================

/** Map an OpenAPI parameter schema to a TypeScript type hint string. */
function openapiTypeToTs(schema: AnySchema): string {
    const t = schema?.type ?? "string";
    switch (t) {
        case "string":
            return "string";
        case "integer":
        case "number":
            return "number";
        case "boolean":
            return "boolean";
        case "array":
            return `${schema.items ? openapiTypeToTs(schema.items) : "unknown"}[]`;
        case "object":
            return "Record<string, unknown>";
        default:
            return "string";
    }
}

/**
 * Determine the request payload type name for an operation. Uses the schema's own
 * `title` when present, otherwise falls back to `<OperationId>Request`.
 */
function requestClassName(schema: AnySchema | undefined, base: string): string {
    if (schema && typeof schema.title === "string") return toPascalCase(schema.title);
    return `${base}Request`;
}

/**
 * Determine the response type name for an operation. Response schemas are usually
 * `allOf` compositions where the inline object member carries the `title`.
 */
function responseClassName(schema: AnySchema | undefined, base: string): string {
    if (schema && typeof schema.title === "string") return toPascalCase(schema.title);
    if (schema && Array.isArray(schema.allOf)) {
        for (const member of schema.allOf) {
            if (member && typeof member.title === "string") return toPascalCase(member.title);
        }
    }
    return `${base}Response`;
}

interface ParamInfo {
    name: string;
    js_name: string;
    required: boolean;
    type: string;
    is_array: boolean;
}

interface OperationInfo {
    method_name: string;
    http_method: string;
    http_method_upper: string;
    url_template: string;
    path_params: ParamInfo[];
    query_params: ParamInfo[];
    has_body: boolean;
    request_class: string | null;
    response_class: string;
    description: string;
}

/** Extract operation metadata from the OpenAPI spec for the client template. */
function buildOperations(spec: AnySchema): OperationInfo[] {
    const ops: OperationInfo[] = [];
    const paramsRegistry: Record<string, any> = spec?.components?.parameters ?? {};
    const httpMethods = ["get", "post", "put", "delete", "patch"];

    for (const [apiPath, methods] of Object.entries<any>(spec?.paths ?? {})) {
        for (const [httpMethod, details] of Object.entries<any>(methods)) {
            if (!httpMethods.includes(httpMethod)) continue;

            const operationId: string = details.operationId;
            const base = toPascalCase(operationId);
            const description: string = details.description ?? details.summary ?? "";

            const pathParams: ParamInfo[] = [];
            const queryParams: ParamInfo[] = [];

            for (let param of details.parameters ?? []) {
                if (param.$ref) {
                    const refName = param.$ref.split("/").pop();
                    param = paramsRegistry[refName];
                }
                const schema = param.schema ?? {};
                const info: ParamInfo = {
                    name: param.name,
                    js_name: toCamelCase(param.name),
                    required: Boolean(param.required),
                    type: openapiTypeToTs(schema),
                    is_array: (schema.type ?? "") === "array",
                };
                if (param.in === "path") pathParams.push(info);
                else if (param.in === "query") queryParams.push(info);
            }

            const requestSchema = details.requestBody?.content?.["application/json"]?.schema;
            const responseSchema =
                details.responses?.["200"]?.content?.["application/json"]?.schema;

            const hasBody = Boolean(details.requestBody);
            const requestClass = hasBody ? requestClassName(requestSchema, base) : null;
            const responseClass = responseClassName(responseSchema, base);

            let urlTemplate = apiPath;
            for (const pp of pathParams) {
                urlTemplate = urlTemplate.replace(
                    "{" + pp.name + "}",
                    "${encodeURIComponent(" + pp.js_name + ")}",
                );
            }

            ops.push({
                method_name: toCamelCase(operationId),
                http_method: httpMethod,
                http_method_upper: httpMethod.toUpperCase(),
                url_template: urlTemplate,
                path_params: pathParams,
                query_params: queryParams,
                has_body: hasBody,
                request_class: requestClass,
                response_class: responseClass,
                description,
            });
        }
    }

    return ops;
}

// ===========================================================================
// Entry point
// ===========================================================================

async function main(): Promise<void> {
    const builder = new SdkBuilder(__dirname);
    await builder.run();
}

main().catch(console.error);
