// This file is automatically generated, do not edit this file

/**
 * Aspected client -- a simple fetch-based TypeScript client for the Aspected Database API.
 */

import type {
    ErrorResponse,
    CreateIndexRequest,
    CreateIndexResponse,
    DeleteIndexResponse,
    GetDocResponse,
    GetIndexResponse,
    ListDocsResponse,
    ListIndexResponse,
    SearchIndexRequest,
    SearchIndexResponse,
    UploadDocsRequest,
    UploadDocsResponse,
} from "./types";

/**
 * Raised when the Aspected API returns a non-success HTTP response.
 */
export class AspectedError extends Error {
    /** HTTP status code. */
    readonly status: number;
    /** HTTP status text. */
    readonly statusText: string;
    /** Server-provided error message, if available. */
    readonly error?: string;

    constructor(status: number, statusText: string, error?: string) {
        let message = `${status} ${statusText}`;
        if (error) {
            message += `: ${error}`;
        }
        super(message);
        this.name = "AspectedError";
        this.status = status;
        this.statusText = statusText;
        this.error = error;
    }
}

/**
 * Client for the Aspected database.
 */
export class AspectedClient {
    private readonly baseUrl: string;
    private readonly init: RequestInit;

    /**
     * @param url Base URL of the Aspected database server (e.g. `"http://localhost:8080"`).
     * @param init Default `RequestInit` options applied to every request.
     */
    constructor(url: string, init: RequestInit = {}) {
        this.baseUrl = url.replace(/\/+$/, "");
        this.init = init;
    }

    // ------------------------------------------------------------------
    // Generated API Methods
    // ------------------------------------------------------------------

    /** Creates, updates, and deletes documents in a single transactional request. */
    async uploadDocs(indexName: string, body: UploadDocsRequest): Promise<UploadDocsResponse> {
        const url = `${this.baseUrl}/indexes/${encodeURIComponent(indexName)}/docs`;
        const resp = await fetch(url, {
            ...this.init,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                ...this.init.headers,
            },
            body: JSON.stringify(body),
        });
        if (!resp.ok) {
            let errorMsg: string | undefined;
            try {
                const errorResult = (await resp.json()) as ErrorResponse;
                errorMsg = errorResult.error;
            } catch {
                // Ignore malformed error bodies.
            }
            throw new AspectedError(resp.status, resp.statusText, errorMsg);
        }
        return (await resp.json()) as UploadDocsResponse;
    }

    /** Returns a paginated list of documents stored in an index. */
    async getDocs(
        indexName: string,
        page?: number,
        limit?: number,
        ids?: string[],
    ): Promise<ListDocsResponse> {
        const params = new URLSearchParams();
        if (page !== undefined) {
            params.append("page", String(page));
        }
        if (limit !== undefined) {
            params.append("limit", String(limit));
        }
        if (ids !== undefined) {
            for (const value of ids) {
                params.append("ids", String(value));
            }
        }
        const query = params.toString();
        const url = `${this.baseUrl}/indexes/${encodeURIComponent(indexName)}/docs${query ? `?${query}` : ""}`;
        const resp = await fetch(url, {
            ...this.init,
            method: "GET",
            headers: {
                ...this.init.headers,
            },
        });
        if (!resp.ok) {
            let errorMsg: string | undefined;
            try {
                const errorResult = (await resp.json()) as ErrorResponse;
                errorMsg = errorResult.error;
            } catch {
                // Ignore malformed error bodies.
            }
            throw new AspectedError(resp.status, resp.statusText, errorMsg);
        }
        return (await resp.json()) as ListDocsResponse;
    }

    /** Returns a single document by ID from an index. */
    async getDoc(indexName: string, docId: string): Promise<GetDocResponse> {
        const url = `${this.baseUrl}/indexes/${encodeURIComponent(indexName)}/docs/${encodeURIComponent(docId)}`;
        const resp = await fetch(url, {
            ...this.init,
            method: "GET",
            headers: {
                ...this.init.headers,
            },
        });
        if (!resp.ok) {
            let errorMsg: string | undefined;
            try {
                const errorResult = (await resp.json()) as ErrorResponse;
                errorMsg = errorResult.error;
            } catch {
                // Ignore malformed error bodies.
            }
            throw new AspectedError(resp.status, resp.statusText, errorMsg);
        }
        return (await resp.json()) as GetDocResponse;
    }

    /** Returns a paginated list of all available indexes. */
    async listIndexes(page?: number, limit?: number): Promise<ListIndexResponse> {
        const params = new URLSearchParams();
        if (page !== undefined) {
            params.append("page", String(page));
        }
        if (limit !== undefined) {
            params.append("limit", String(limit));
        }
        const query = params.toString();
        const url = `${this.baseUrl}/indexes${query ? `?${query}` : ""}`;
        const resp = await fetch(url, {
            ...this.init,
            method: "GET",
            headers: {
                ...this.init.headers,
            },
        });
        if (!resp.ok) {
            let errorMsg: string | undefined;
            try {
                const errorResult = (await resp.json()) as ErrorResponse;
                errorMsg = errorResult.error;
            } catch {
                // Ignore malformed error bodies.
            }
            throw new AspectedError(resp.status, resp.statusText, errorMsg);
        }
        return (await resp.json()) as ListIndexResponse;
    }

    /** Returns detailed metadata about a single index, including its schema and HNSW parameters. */
    async getIndex(indexName: string): Promise<GetIndexResponse> {
        const url = `${this.baseUrl}/indexes/${encodeURIComponent(indexName)}`;
        const resp = await fetch(url, {
            ...this.init,
            method: "GET",
            headers: {
                ...this.init.headers,
            },
        });
        if (!resp.ok) {
            let errorMsg: string | undefined;
            try {
                const errorResult = (await resp.json()) as ErrorResponse;
                errorMsg = errorResult.error;
            } catch {
                // Ignore malformed error bodies.
            }
            throw new AspectedError(resp.status, resp.statusText, errorMsg);
        }
        return (await resp.json()) as GetIndexResponse;
    }

    /** Creates a new index with the given name and configuration. */
    async createIndex(indexName: string, body: CreateIndexRequest): Promise<CreateIndexResponse> {
        const url = `${this.baseUrl}/indexes/${encodeURIComponent(indexName)}`;
        const resp = await fetch(url, {
            ...this.init,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                ...this.init.headers,
            },
            body: JSON.stringify(body),
        });
        if (!resp.ok) {
            let errorMsg: string | undefined;
            try {
                const errorResult = (await resp.json()) as ErrorResponse;
                errorMsg = errorResult.error;
            } catch {
                // Ignore malformed error bodies.
            }
            throw new AspectedError(resp.status, resp.statusText, errorMsg);
        }
        return (await resp.json()) as CreateIndexResponse;
    }

    /** Deletes an index and removes its persisted data from disk. */
    async deleteIndex(indexName: string): Promise<DeleteIndexResponse> {
        const url = `${this.baseUrl}/indexes/${encodeURIComponent(indexName)}`;
        const resp = await fetch(url, {
            ...this.init,
            method: "DELETE",
            headers: {
                ...this.init.headers,
            },
        });
        if (!resp.ok) {
            let errorMsg: string | undefined;
            try {
                const errorResult = (await resp.json()) as ErrorResponse;
                errorMsg = errorResult.error;
            } catch {
                // Ignore malformed error bodies.
            }
            throw new AspectedError(resp.status, resp.statusText, errorMsg);
        }
        return (await resp.json()) as DeleteIndexResponse;
    }

    /** Performs a k-nearest-neighbour search against an existing index. */
    async searchIndex(indexName: string, body: SearchIndexRequest): Promise<SearchIndexResponse> {
        const url = `${this.baseUrl}/indexes/${encodeURIComponent(indexName)}/search`;
        const resp = await fetch(url, {
            ...this.init,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                ...this.init.headers,
            },
            body: JSON.stringify(body),
        });
        if (!resp.ok) {
            let errorMsg: string | undefined;
            try {
                const errorResult = (await resp.json()) as ErrorResponse;
                errorMsg = errorResult.error;
            } catch {
                // Ignore malformed error bodies.
            }
            throw new AspectedError(resp.status, resp.statusText, errorMsg);
        }
        return (await resp.json()) as SearchIndexResponse;
    }
}
