/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `ApiTypes`'s JSON-Schema
 * via the `definition` "SearchIndexRequest".
 */
export type SearchIndexRequest = QuerySearch | DocSearch;

export interface ApiTypes {}
/**
 * This interface was referenced by `ApiTypes`'s JSON-Schema
 * via the `definition` "SuccessResponse".
 */
export interface SuccessResponse {
    /**
     * Time taken to process the request in milliseconds.
     */
    time?: number;
    /**
     * Status message indicating success.
     */
    status?: string;
}
/**
 * This interface was referenced by `ApiTypes`'s JSON-Schema
 * via the `definition` "ErrorResponse".
 */
export interface ErrorResponse {
    /**
     * Human-readable error message.
     */
    error?: string;
}
/**
 * This interface was referenced by `ApiTypes`'s JSON-Schema
 * via the `definition` "IndexServiceAspect".
 */
export interface Aspect {
    name: string;
    type: string;
    path: string;
    settings: {
        [k: string]: unknown;
    };
    multiplier?: number;
}
/**
 * This interface was referenced by `ApiTypes`'s JSON-Schema
 * via the `definition` "IndexServiceDocEntry".
 */
export interface DocEntry {
    id: string;
    doc: {
        [k: string]: unknown;
    };
    vector: number[];
    accessList?: string[];
}
/**
 * This interface was referenced by `ApiTypes`'s JSON-Schema
 * via the `definition` "UploadDocsRequest".
 */
export interface UploadDocsRequest {
    data: (UpsertOperation | DeleteOperation)[];
    policy?: UploadDocsRequestPolicy;
}
/**
 * Create or update a document.
 */
export interface UpsertOperation {
    id: string;
    doc: {};
    vectors?: {
        [k: string]: number[];
    };
    accessList?: string[];
    policy?: UpsertOperationPolicy;
}
export interface UpsertOperationPolicy {
    duplicate?: "Replace" | "Ignore" | "Fail";
}
/**
 * Delete a document.
 */
export interface DeleteOperation {
    id: string;
    doc: null;
    policy?: DeleteOperationPolicy;
}
export interface DeleteOperationPolicy {
    missing?: "Ignore" | "Fail";
}
export interface UploadDocsRequestPolicy {
    duplicate?: "Replace" | "Ignore" | "Fail";
    missing?: "Ignore" | "Fail";
}
/**
 * This interface was referenced by `ApiTypes`'s JSON-Schema
 * via the `definition` "UploadDocsResponse".
 */
export interface UploadDocsResponse extends SuccessResponse {
    data: UpdateResult;
}
export interface UpdateResult {
    created: string[];
    updated: string[];
    deleted: string[];
}
/**
 * This interface was referenced by `ApiTypes`'s JSON-Schema
 * via the `definition` "GetDocsResponse".
 */
export interface ListDocsResponse extends SuccessResponse {
    total: number;
    page: number;
    limit: number;
    data: DocEntry[];
}
/**
 * This interface was referenced by `ApiTypes`'s JSON-Schema
 * via the `definition` "GetDocResponse".
 */
export interface GetDocResponse extends SuccessResponse {
    data: DocEntry;
}
/**
 * This interface was referenced by `ApiTypes`'s JSON-Schema
 * via the `definition` "ListIndexesResponse".
 */
export interface ListIndexResponse extends SuccessResponse {
    total: number;
    page: number;
    limit: number;
    data: ListIndexResponseData[];
}
export interface ListIndexResponseData {
    name: string;
}
/**
 * This interface was referenced by `ApiTypes`'s JSON-Schema
 * via the `definition` "GetIndexResponse".
 */
export interface GetIndexResponse extends SuccessResponse {
    data: Index;
}
export interface Index {
    name: string;
    idSize: number;
    numDims: number;
    distanceType: "Manhattan" | "Euclidean" | "DotProduct" | "Cosine";
    schema: Aspect[];
    hnsw: Hnsw;
}
export interface Hnsw {
    M: number;
    Mmax: number;
    Mmax0: number;
    mL: number;
    efConstruction: number;
    efSearch: number;
    extendCandidates: boolean;
    keepPrunedConnections: boolean;
    maxStoreSize: number;
}
/**
 * This interface was referenced by `ApiTypes`'s JSON-Schema
 * via the `definition` "CreateIndexRequest".
 */
export interface CreateIndexRequest {
    idSize: number;
    distanceType?: "Manhattan" | "Euclidean" | "DotProduct" | "Cosine";
    schema: Aspect[];
    hnsw?: HNSWConfig;
}
export interface HNSWConfig {
    M?: number;
    Mmax?: number;
    Mmax0?: number;
    mL?: number;
    efConstruction?: number;
    efSearch?: number;
    extendCandidates?: boolean;
    keepPrunedConnections?: boolean;
    maxStoreSize?: number;
}
/**
 * This interface was referenced by `ApiTypes`'s JSON-Schema
 * via the `definition` "CreateIndexResponse".
 */
export interface CreateIndexResponse extends SuccessResponse {
    data: CreateIndexResponseData;
}
export interface CreateIndexResponseData {
    created: boolean;
}
/**
 * This interface was referenced by `ApiTypes`'s JSON-Schema
 * via the `definition` "DeleteIndexResponse".
 */
export interface DeleteIndexResponse extends SuccessResponse {
    data: DeleteIndexResponseData;
}
export interface DeleteIndexResponseData {
    deleted: boolean;
}
export interface QuerySearch {
    /**
     * Number of nearest neighbours to return.
     */
    k: number;
    /**
     * Map of aspect names to query values. Each value can be a primitive (string, number, boolean), object, array, null, or a raw vector specified as `{"$raw": [number, ...]}`.
     *
     */
    query: {
        [k: string]: unknown;
    };
    /**
     * Optional map of aspect names to weight multipliers.
     */
    weights?: {
        [k: string]: number;
    };
    /**
     * Optional access filter list. Null entries are permitted.
     */
    accessFilter?: (string | null)[];
    /**
     * Whether to include the stored document in each result.
     */
    withDocs?: boolean;
    /**
     * Whether to include the vector in each result.
     */
    withVectors?: boolean;
    /**
     * Whether to include an explanation of search aspects in each result.
     */
    withExplanation?: boolean;
}
export interface DocSearch {
    /**
     * Number of nearest neighbours to return.
     */
    k: number;
    /**
     * A document object to use as the query.
     */
    doc: {
        [k: string]: unknown;
    };
    /**
     * Optional map of aspect names to weight multipliers.
     */
    weights?: {
        [k: string]: number;
    };
    /**
     * Optional access filter list. Null entries are permitted.
     */
    accessFilter?: (string | null)[];
    /**
     * Whether to include the stored document in each result.
     */
    withDocs?: boolean;
    /**
     * Whether to include the vector in each result.
     */
    withVectors?: boolean;
    /**
     * Whether to include an explanation of search aspects in each result.
     */
    withExplanation?: boolean;
}
/**
 * This interface was referenced by `ApiTypes`'s JSON-Schema
 * via the `definition` "SearchIndexResponse".
 */
export interface SearchIndexResponse extends SuccessResponse {
    data: SearchResultRow[];
}
export interface SearchResultRow {
    id: string;
    distance: number;
    vector?: number[];
    doc?: {
        [k: string]: unknown;
    };
    explanation?: SearchResultExplanation[];
}
export interface SearchResultExplanation {
    name: string;
    value: unknown;
    distance?: number;
}
